import{a as M,S as q,i as c}from"./assets/vendor-BSTwZ_tR.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const R="https://pixabay.com/api/",$="53047791-da6bf0178b39a3cb2727ecc21",A=15,_=M.create({baseURL:R,params:{key:$,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function y(a,o=1){try{return(await _.get("",{params:{q:a,page:o,per_page:A}})).data}catch(t){return console.error("Error fetching images:",t.message),{totalHits:0,hits:[]}}}const h=document.querySelector(".gallery"),b=document.querySelector(".span-loader"),i=document.querySelector(".form-btn-load");let d=null;function x(){d||(d=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:.9,animationSpeed:300,fadeSpeed:250,close:!0,closeText:"×",enableKeyboard:!0,nav:!0,doubleTapZoom:1.5,scrollZoom:!1,disableRightClick:!0,docClose:!0,history:!1}))}function L(a){const o=a.map(({largeImageURL:t,webformatURL:l,tags:e,likes:r,views:n,comments:P,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-img" src="${l}" alt="${e}" />
          <ul class="gallery-desc">
            <li><span>Likes:</span> ${r}</li>
            <li><span>Views:</span> ${n}</li>
            <li><span>Comments:</span> ${P}</li>
            <li><span>Downloads:</span> ${v}</li>
          </ul>
        </a>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",o),d?d.refresh():x()}function I(){h.innerHTML=""}function w(){b.classList.add("loader"),i.disabled=!0}function u(){b.classList.remove("loader"),i.disabled=!1}function f(){i.classList.add("is-active"),i.disabled=!1}function S(){i.classList.remove("is-active"),i.disabled=!0}const E=document.querySelector(".form"),O=document.querySelector(".form-btn-load");let p,s,m;const B=15;E.addEventListener("submit",G);O.addEventListener("click",T);function g(a){c.error({message:a,position:"topRight"})}async function G(a){a.preventDefault();const o=a.target.elements["search-text"].value.trim();if(!o){c.warning({message:"Please enter a search query!",position:"topRight"});return}p=o,s=1,E.reset(),S(),I();try{w();const t=await y(p,s);if(u(),!t.totalHits){g("No images found. Try another query.");return}m=Math.ceil(t.totalHits/B),L(t.hits),s<m?f():c.info({message:"End of search results",position:"topRight"})}catch(t){console.error(t),u(),g("Something went wrong. Please try again!")}}async function T(a){a.preventDefault(),S(),s++;try{w();const o=await y(p,s);u(),L(o.hits);const t=document.querySelector(".gallery-item:last-child");t&&t.scrollIntoView({behavior:"smooth",block:"start"}),s<m?f():c.info({message:"End of search results",position:"topRight"})}catch(o){console.error(o),s--,u(),f(),g("Something went wrong. Please try again!")}}
//# sourceMappingURL=index.js.map
